login: &login
  adapter: oracle_enhanced
  username: rails
  password: rails

development:
  database: pdm_otomelara
  <<: *login

test:
  database: oto_test
  <<: *login

production:
  database: pdm_otomelara
  <<: *login
