AUTH_KO: Invalid username/password
AUTH_OK: User successfully logged in
AUTOPROMOTE: Auto-promoted by PlmExplorer
CONN_KO: Connection to server failed
LOGGED_OUT: Logged out
NO_FILE: File not available
REPORT_SUBMITTED: Report submitted
REPORT_ERROR: Record doesn't exist!
STARS: "****************************** "
