FIND:
  - type: PART
    label: Part
    iconclass: table_gear
    title: Find Part
  - type: DOCUMENT
    label: Document
    iconclass: book_open
    title: Find Document
  - type: WORKAUTH
    label: Workauth
    iconclass: application_form_edit
    title: Find Workauth
  - type: SOFTWARE
    label: Software
    iconclass: page_white_code
    title: Find Software
  - type: GENERIC
    label: Generic
    iconclass: page_white
    title: Find Generic Object
    
REPORT:
  - type: bomnew
    label: BOMNEW
    iconclass: report
    title: Distinta Tecnica OTO Melara
  - type: bomvalnew
    label: BOMVALNEW
    iconclass: report
    title: Distinte Tecniche a valle di una Distinta
  - type: ei
    label: EI
    iconclass: report
    title: Elenco End-Item di appartenenza
  - type: odm
    label: ODM
    iconclass: report
    title: Anagrafica/Elenco Ordini di Modifica (PA007)
  - type: req
    label: REQ
    iconclass: report
    title: Anagrafica/Elenco WorkAuth tipo Request
  - type: wa
    label: WA
    iconclass: report
    title: Anagrafica/Elenco WorkAuth tipo Change e Task
  - type: imgexp
    label: IMGEXP
    iconclass: report
    title: Estrazione immagini
    rule: image_exporter
