FIND:
  - type: PART
    label: Part
    iconclass: table_gear
  - type: DOCUMENT
    label: Document
    iconclass: book_open
  - type: WORKAUTH
    label: Workauth
    iconclass: application_form_edit
  - type: SOFTWARE
    label: Software
    iconclass: page_white_code
  - type: GENERIC
    label: Generic
    iconclass: page_white
    
REPORT:
  - type: REPORT
    label: Report 1
    iconclass: report
  - type: REPORT
    label: Report 2
    iconclass: report
  - type: REPORT
    label: Report 3
    iconclass: report
  - type: REPORT
    label: Report 4
    iconclass: report
