FIND:
  - type: PART
    label: Part
    iconclass: table_gear
  - type: DOCUMENT
    label: Document
    iconclass: book_open
  - type: WORKAUTH
    label: Workauth
    iconclass: application_form_edit
  - type: SOFTWARE
    label: Software
    iconclass: page_white_code
  - type: GENERIC
    label: Generic
    iconclass: page_white
    
REPORT:
  - type: OTO-BOMNEW
    label: BOMNEW
    iconclass: report
  - type: OTO-BOMVALNEW
    label: BOMVALNEW
    iconclass: report
  - type: OTO-EI
    label: EI
    iconclass: report
  - type: OTO-ODM
    label: ODM
    iconclass: report
  - type: OTO-REQ
    label: REQ
    iconclass: report
  - type: OTO-WA
    label: WA
    iconclass: report
